### ISSUE TITLE
nglview not showing up

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/MDAnalysisWorkshop2023#17]
nglview currently doesn't appear to be working properly in the colab notebooks, nor when I try run from my laptop. The code runs, but nothing shows up.

I believe we've had similar problems in the past so hopefully this isn't a difficult fix - otherwise nglview isn't essential to the workshop, but it is nice to include.

**Comment by lilyminium** [comment]
Sigh. After a lot of trial and error, this config works:

Cell 1:

```
# NBVAL_SKIP
!pip install condacolab
import condacolab
condacolab.install_mambaforge()
```

Cell 2:
```
!mamba install -n base -c conda-forge mdanalysis mdanalysistests mdanalysisdata nglview==3.0.3 ipywidgets==7.6.0

from google.colab import output
output.enable_custom_widget_manager()
```

I took this from an OpenFF workshop, so let me do some more trial and error to figure out exactly which parts of these are the fix and I'll open a PR tomorrow.

As for running it locally, I've always found that I have to start the NB server in an environment with NGLView installed instead of just launching a kernel with it, if that helps! (I checked and can still use NGLView locally personally)
